# Generated by Django 2.2.4 on 2020-01-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20200110_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwaHaeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('skin_type', models.CharField(choices=[('dry', 'Dry'), ('oily', 'Oily'), ('sensitive', 'Sensitive')], max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('superhost', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_secret', models.CharField(blank=True, default='', max_length=120)),
                ('login_method', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook'), ('naver', 'Naver')], default='email', max_length=50)),
                ('point', models.IntegerField(default=0)),
                ('favorite_ingredient', models.ManyToManyField(null=True, related_name='HwaHaeusers', to='products.Ingredient')),
                ('favorite_products', models.ManyToManyField(null=True, related_name='HwaHaeusers', to='products.Product')),
            ],
        ),
    ]
