# Generated by Django 2.2.4 on 2020-01-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
