# Generated by Django 2.2.4 on 2020-01-10 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200110_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwahaeuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hwahaeuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hwahaeuser',
            name='favs_ingredients',
            field=models.ManyToManyField(related_name='users', to='products.Ingredient'),
        ),
        migrations.AlterField(
            model_name='hwahaeuser',
            name='favs_products',
            field=models.ManyToManyField(related_name='users', to='products.Product'),
        ),
    ]
