# Generated by Django 2.2.4 on 2020-01-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200121_1157'),
        ('users', '0002_user_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scrap_reviews',
            field=models.ManyToManyField(related_name='users', to='reviews.Review'),
        ),
    ]
