# Generated by Django 2.2.4 on 2020-01-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200110_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hwahaeuser',
            old_name='superhost',
            new_name='superuser',
        ),
    ]
