# Generated by Django 2.2.4 on 2020-01-21 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200115_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='favorites',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
