# Generated by Django 2.2.4 on 2020-01-21 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_auto_20200121_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='favorites',
        ),
        migrations.AddField(
            model_name='review',
            name='favorite_users',
            field=models.ManyToManyField(related_name='reviews_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
