# Generated by Django 2.2.4 on 2020-01-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('skincare', 'Skin care'), ('maskpack', 'Mask pack'), ('suncare', 'Sun care'), ('basemakeup', 'Base makeup')], default='skincare', max_length=11),
        ),
    ]
